#!/usr/bin/env python3
"""Generate the P02 engineering ER reference from SQLAlchemy metadata."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
API_SRC = REPO_ROOT / "services" / "api" / "src"
sys.path.insert(0, str(API_SRC))

from momo_fdvs import models as _models  # noqa: E402, F401
from momo_fdvs.extensions import db  # noqa: E402

OUTPUT = REPO_ROOT / "docs" / "architecture" / "P02_IMPLEMENTED_ER.md"


def render() -> str:
    lines = [
        "# P02 Implemented Engineering ER Reference",
        "",
        "> Generated by `python scripts/export_er.py`; do not edit the Mermaid block manually.",
        "",
        "```mermaid",
        "erDiagram",
    ]
    for table in sorted(db.metadata.tables.values(), key=lambda item: item.name):
        lines.append(f"    {table.name.upper()} {{")
        for column in table.columns:
            markers = []
            if column.primary_key:
                markers.append("PK")
            if column.foreign_keys:
                markers.append("FK")
            marker = f" {' '.join(markers)}" if markers else ""
            type_name = (
                str(column.type).replace(" ", "_").replace("(", "_").replace(")", "")
            )
            lines.append(f"        {type_name} {column.name}{marker}")
        lines.append("    }")
    relations: set[tuple[str, str]] = set()
    for table in db.metadata.tables.values():
        for foreign_key in table.foreign_keys:
            relations.add((foreign_key.column.table.name.upper(), table.name.upper()))
    for parent, child in sorted(relations):
        lines.append(f'    {parent} ||--o{{ {child} : "references"')
    lines.extend(
        [
            "```",
            "",
            "## Differences from the Chapter Three conceptual diagram",
            "",
            "- Authentication sessions, password-reset hashes and idempotency records are explicit security tables.",
            "- Automated analysis, verification and human case decisions are separate immutable evidence records.",
            "- Object storage is represented by private object keys and SHA-256 metadata rather than public image URLs.",
            "- Version registries and per-stage execution rows preserve reproducibility and partial-analysis evidence.",
            "- `users.must_change_password` is an implementation field added to enforce safe bootstrap credential rotation.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print("ER reference is out of date")
            return 1
        print("ER reference matches SQLAlchemy metadata")
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
