"""implement P02 domain schema

Revision ID: 20260809_0002
Revises: 20260809_0001
Create Date: 2026-08-09 20:12:06.256059
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260809_0002"
down_revision: str | None = "20260809_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.create_table(
        "roles",
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.CheckConstraint(
            "code IN ('USER', 'ADMIN', 'INVESTIGATOR')", name=op.f("ck_roles_code_valid")
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_roles")),
    )
    op.create_table(
        "users",
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column("phone_e164", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'DISABLED', 'PENDING')", name=op.f("ck_users_status_valid")
        ),
        sa.CheckConstraint("token_version >= 1", name=op.f("ck_users_token_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index("ix_users_status", "users", ["status"], unique=False)
    op.create_table(
        "admin_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("staff_reference", sa.String(length=100), nullable=True),
        sa.Column("department", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_admin_profiles_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_admin_profiles")),
        sa.UniqueConstraint("staff_reference", name=op.f("uq_admin_profiles_staff_reference")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_role_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("user_agent_hash", sa.String(length=64), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('SUCCESS', 'FAILURE', 'DENIED')", name=op.f("ck_audit_logs_outcome_valid")
        ),
        sa.CheckConstraint(
            "ip_hash IS NULL OR char_length(ip_hash) = 64",
            name=op.f("ck_audit_logs_ip_hash_length"),
        ),
        sa.CheckConstraint(
            "user_agent_hash IS NULL OR char_length(user_agent_hash) = 64",
            name=op.f("ck_audit_logs_user_agent_hash_length"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_logs_action_created", "audit_logs", ["action", "created_at"], unique=False
    )
    op.create_index(
        "ix_audit_logs_actor_created", "audit_logs", ["actor_id", "created_at"], unique=False
    )
    op.create_index("ix_audit_logs_created_at", "audit_logs", ["created_at"], unique=False)
    op.create_index("ix_audit_logs_request_id", "audit_logs", ["request_id"], unique=False)
    op.create_index(
        "ix_audit_logs_target", "audit_logs", ["target_type", "target_id"], unique=False
    )
    op.create_table(
        "fraud_rule_sets",
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("risk_weights", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("thresholds", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("activated_by", sa.Uuid(), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'ACTIVE', 'RETIRED')", name=op.f("ck_fraud_rule_sets_status_valid")
        ),
        sa.CheckConstraint(
            "row_version >= 1", name=op.f("ck_fraud_rule_sets_row_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["activated_by"],
            ["users.id"],
            name=op.f("fk_fraud_rule_sets_activated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_fraud_rule_sets_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fraud_rule_sets")),
        sa.UniqueConstraint("version", name=op.f("uq_fraud_rule_sets_version")),
    )
    op.create_index(
        "uq_fraud_rule_sets_active",
        "fraud_rule_sets",
        ["status"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "idempotency_records",
        sa.Column("principal_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=100), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(key_hash) = 64", name=op.f("ck_idempotency_records_key_hash_length")
        ),
        sa.CheckConstraint(
            "char_length(request_hash) = 64",
            name=op.f("ck_idempotency_records_request_hash_length"),
        ),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["users.id"],
            name=op.f("fk_idempotency_records_principal_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint(
            "principal_id",
            "scope",
            "key_hash",
            name=op.f("uq_idempotency_records_principal_id_scope_key_hash"),
        ),
    )
    op.create_index(
        "ix_idempotency_records_expires_at", "idempotency_records", ["expires_at"], unique=False
    )
    op.create_table(
        "model_versions",
        sa.Column("model_type", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("artifact_uri", sa.String(length=1000), nullable=False),
        sa.Column("artifact_sha256", sa.String(length=64), nullable=False),
        sa.Column("input_schema_hash", sa.String(length=64), nullable=False),
        sa.Column("preprocessing_version", sa.String(length=100), nullable=False),
        sa.Column("framework_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dataset_manifest_hash", sa.String(length=64), nullable=True),
        sa.Column("split_hash", sa.String(length=64), nullable=True),
        sa.Column("training_commit_sha", sa.String(length=40), nullable=True),
        sa.Column("model_card_key", sa.String(length=500), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("activated_by", sa.Uuid(), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "model_type IN ('STRUCTURED', 'IMAGE')", name=op.f("ck_model_versions_model_type_valid")
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'READY', 'ACTIVE', 'RETIRED', 'FAILED')",
            name=op.f("ck_model_versions_status_valid"),
        ),
        sa.CheckConstraint(
            "char_length(artifact_sha256) = 64",
            name=op.f("ck_model_versions_artifact_sha256_length"),
        ),
        sa.CheckConstraint(
            "char_length(input_schema_hash) = 64", name=op.f("ck_model_versions_schema_hash_length")
        ),
        sa.CheckConstraint(
            "dataset_manifest_hash IS NULL OR char_length(dataset_manifest_hash) = 64",
            name=op.f("ck_model_versions_manifest_hash_length"),
        ),
        sa.CheckConstraint(
            "split_hash IS NULL OR char_length(split_hash) = 64",
            name=op.f("ck_model_versions_split_hash_length"),
        ),
        sa.ForeignKeyConstraint(
            ["activated_by"],
            ["users.id"],
            name=op.f("fk_model_versions_activated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_model_versions_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_versions")),
        sa.UniqueConstraint(
            "model_type", "name", "version", name=op.f("uq_model_versions_model_type_name_version")
        ),
    )
    op.create_index(
        "uq_model_versions_active_type_name",
        "model_versions",
        ["model_type", "name"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=True),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery_status", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(target_type IS NULL AND target_id IS NULL) OR (target_type IS NOT NULL AND target_id IS NOT NULL)",
            name=op.f("ck_notifications_target_pair_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_user_read_created",
        "notifications",
        ["user_id", "read_at", "created_at"],
        unique=False,
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requested_ip_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(token_hash) = 64", name=op.f("ck_password_reset_tokens_token_hash_length")
        ),
        sa.CheckConstraint(
            "requested_ip_hash IS NULL OR char_length(requested_ip_hash) = 64",
            name=op.f("ck_password_reset_tokens_requested_ip_hash_length"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_password_reset_tokens_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_reset_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_password_reset_tokens_token_hash")),
    )
    op.create_index(
        "ix_password_reset_tokens_user_id", "password_reset_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "receipt_templates",
        sa.Column("provider_code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("parser_version", sa.String(length=100), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("activated_by", sa.Uuid(), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'ACTIVE', 'RETIRED')",
            name=op.f("ck_receipt_templates_status_valid"),
        ),
        sa.CheckConstraint(
            "row_version >= 1", name=op.f("ck_receipt_templates_row_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["activated_by"],
            ["users.id"],
            name=op.f("fk_receipt_templates_activated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_receipt_templates_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipt_templates")),
        sa.UniqueConstraint(
            "provider_code", "version", name=op.f("uq_receipt_templates_provider_code_version")
        ),
    )
    op.create_index(
        "uq_receipt_templates_active_provider",
        "receipt_templates",
        ["provider_code"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "reference_import_batches",
        sa.Column("source_label", sa.String(length=200), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("valid_rows", sa.Integer(), nullable=False),
        sa.Column("invalid_rows", sa.Integer(), nullable=False),
        sa.Column("invalid_report_key", sa.String(length=500), nullable=True),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('UPLOADED', 'VALIDATED', 'COMMITTED', 'FAILED')",
            name=op.f("ck_reference_import_batches_status_valid"),
        ),
        sa.CheckConstraint(
            "char_length(file_sha256) = 64",
            name=op.f("ck_reference_import_batches_file_hash_length"),
        ),
        sa.CheckConstraint(
            "invalid_rows >= 0", name=op.f("ck_reference_import_batches_invalid_rows_nonnegative")
        ),
        sa.CheckConstraint(
            "total_rows >= 0", name=op.f("ck_reference_import_batches_total_rows_nonnegative")
        ),
        sa.CheckConstraint(
            "valid_rows >= 0", name=op.f("ck_reference_import_batches_valid_rows_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            name=op.f("fk_reference_import_batches_uploaded_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_import_batches")),
        sa.UniqueConstraint(
            "source_label",
            "file_sha256",
            name=op.f("uq_reference_import_batches_source_label_file_sha256"),
        ),
    )
    op.create_index(
        "ix_reference_import_batches_file_sha256",
        "reference_import_batches",
        ["file_sha256"],
        unique=False,
    )
    op.create_table(
        "refresh_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoke_reason", sa.String(length=50), nullable=True),
        sa.Column("replaced_by_id", sa.Uuid(), nullable=True),
        sa.Column("user_agent_hash", sa.String(length=64), nullable=True),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(token_hash) = 64", name=op.f("ck_refresh_sessions_token_hash_length")
        ),
        sa.CheckConstraint(
            "ip_hash IS NULL OR char_length(ip_hash) = 64",
            name=op.f("ck_refresh_sessions_ip_hash_length"),
        ),
        sa.CheckConstraint(
            "user_agent_hash IS NULL OR char_length(user_agent_hash) = 64",
            name=op.f("ck_refresh_sessions_user_agent_hash_length"),
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["refresh_sessions.id"],
            name=op.f("fk_refresh_sessions_replaced_by_id_refresh_sessions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_sessions_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_sessions_token_hash")),
    )
    op.create_index(
        "ix_refresh_sessions_expires_at", "refresh_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_refresh_sessions_family_id", "refresh_sessions", ["family_id"], unique=False
    )
    op.create_index("ix_refresh_sessions_user_id", "refresh_sessions", ["user_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("provider_code", sa.String(length=50), nullable=True),
        sa.Column("display_reference_masked", sa.String(length=100), nullable=True),
        sa.Column("latest_analysis_run_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'UPLOADED', 'OCR_PENDING', 'OCR_REVIEW', 'READY', 'ANALYSIS_QUEUED', 'ANALYSING', 'COMPLETED', 'PARTIAL', 'FAILED', 'DELETED')",
            name=op.f("ck_transactions_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_transactions_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
    )
    op.create_index(
        "ix_transactions_provider_code", "transactions", ["provider_code"], unique=False
    )
    op.create_index(
        "ix_transactions_status_created", "transactions", ["status", "created_at"], unique=False
    )
    op.create_index(
        "ix_transactions_user_created", "transactions", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_code", sa.String(length=30), nullable=False),
        sa.Column("granted_by", sa.Uuid(), nullable=True),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["users.id"],
            name=op.f("fk_user_roles_granted_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_code"],
            ["roles.code"],
            name=op.f("fk_user_roles_role_code_roles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_code", name=op.f("pk_user_roles")),
    )
    op.create_table(
        "fraud_cases",
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("reporter_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("assigned_to", sa.Uuid(), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('USER_REPORT', 'AUTO_HIGH_RISK', 'ADMIN')",
            name=op.f("ck_fraud_cases_source_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'ASSIGNED', 'IN_REVIEW', 'DECIDED', 'CLOSED', 'REOPENED')",
            name=op.f("ck_fraud_cases_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
            name=op.f("fk_fraud_cases_assigned_to_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["users.id"],
            name=op.f("fk_fraud_cases_reporter_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_fraud_cases_transaction_id_transactions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fraud_cases")),
    )
    op.create_index(
        "ix_fraud_cases_status_assigned_opened",
        "fraud_cases",
        ["status", "assigned_to", "opened_at"],
        unique=False,
    )
    op.create_index(
        "ix_fraud_cases_transaction_id", "fraud_cases", ["transaction_id"], unique=False
    )
    op.create_index(
        "uq_fraud_cases_active_transaction_source",
        "fraud_cases",
        ["transaction_id", "source"],
        unique=True,
        postgresql_where=sa.text("status IN ('OPEN', 'ASSIGNED', 'IN_REVIEW', 'REOPENED')"),
    )
    op.create_table(
        "fraud_rules",
        sa.Column("rule_set_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("condition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("score_contribution", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("reason_template", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity IN ('INFORMATIONAL', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
            name=op.f("ck_fraud_rules_severity_valid"),
        ),
        sa.CheckConstraint(
            "score_contribution >= 0", name=op.f("ck_fraud_rules_score_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["rule_set_id"],
            ["fraud_rule_sets.id"],
            name=op.f("fk_fraud_rules_rule_set_id_fraud_rule_sets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fraud_rules")),
        sa.UniqueConstraint("rule_set_id", "code", name=op.f("uq_fraud_rules_rule_set_id_code")),
    )
    op.create_index("ix_fraud_rules_rule_set_id", "fraud_rules", ["rule_set_id"], unique=False)
    op.create_table(
        "receipts",
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("object_key", sa.String(length=500), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.String(length=50), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("width_px", sa.Integer(), nullable=False),
        sa.Column("height_px", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("perceptual_hash", sa.String(length=32), nullable=False),
        sa.Column("quality_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("quality_warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("storage_version", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(sha256) = 64", name=op.f("ck_receipts_sha256_length")),
        sa.CheckConstraint("height_px > 0", name=op.f("ck_receipts_height_positive")),
        sa.CheckConstraint(
            "quality_score IS NULL OR (quality_score >= 0 AND quality_score <= 1)",
            name=op.f("ck_receipts_quality_score_range"),
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_receipts_size_positive")),
        sa.CheckConstraint("width_px > 0", name=op.f("ck_receipts_width_positive")),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_receipts_transaction_id_transactions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipts")),
        sa.UniqueConstraint("object_key", name=op.f("uq_receipts_object_key")),
        sa.UniqueConstraint("transaction_id", name=op.f("uq_receipts_transaction_id")),
    )
    op.create_index("ix_receipts_perceptual_hash", "receipts", ["perceptual_hash"], unique=False)
    op.create_index("ix_receipts_sha256", "receipts", ["sha256"], unique=False)
    op.create_table(
        "reference_transactions",
        sa.Column("import_batch_id", sa.Uuid(), nullable=False),
        sa.Column("provider_code", sa.String(length=50), nullable=False),
        sa.Column("transaction_reference", sa.String(length=150), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("sender_name_normalised", sa.String(length=200), nullable=True),
        sa.Column("sender_phone_e164", sa.String(length=20), nullable=True),
        sa.Column("receiver_name_normalised", sa.String(length=200), nullable=True),
        sa.Column("receiver_phone_e164", sa.String(length=20), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("transaction_status", sa.String(length=50), nullable=True),
        sa.Column("source_system_id", sa.String(length=150), nullable=True),
        sa.Column("raw_row", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount >= 0", name=op.f("ck_reference_transactions_amount_nonnegative")
        ),
        sa.CheckConstraint(
            "char_length(currency) = 3", name=op.f("ck_reference_transactions_currency_length")
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["reference_import_batches.id"],
            name=op.f("fk_reference_transactions_import_batch_id_reference_import_batches"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_transactions")),
        sa.UniqueConstraint(
            "provider_code",
            "transaction_reference",
            "import_batch_id",
            name="uq_reference_transactions_batch_reference",
        ),
    )
    op.create_index(
        "ix_reference_transactions_occurred_at",
        "reference_transactions",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_reference_transactions_provider_reference",
        "reference_transactions",
        ["provider_code", "transaction_reference"],
        unique=False,
    )
    op.create_index(
        "uq_reference_transactions_source_id",
        "reference_transactions",
        ["provider_code", "transaction_reference", "source_system_id"],
        unique=True,
        postgresql_where=sa.text("source_system_id IS NOT NULL"),
    )
    op.create_table(
        "case_decisions",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("decided_by", sa.Uuid(), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('CONFIRMED', 'DISMISSED', 'ESCALATED')",
            name=op.f("ck_case_decisions_outcome_valid"),
        ),
        sa.CheckConstraint(
            "char_length(trim(reason)) > 0", name=op.f("ck_case_decisions_reason_required")
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["fraud_cases.id"],
            name=op.f("fk_case_decisions_case_id_fraud_cases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["users.id"],
            name=op.f("fk_case_decisions_decided_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["case_decisions.id"],
            name=op.f("fk_case_decisions_supersedes_id_case_decisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_decisions")),
    )
    op.create_index("ix_case_decisions_case_id", "case_decisions", ["case_id"], unique=False)
    op.create_table(
        "case_events",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type <> 'DECISION' OR (reason IS NOT NULL AND char_length(trim(reason)) > 0)",
            name=op.f("ck_case_events_decision_reason_required"),
        ),
        sa.CheckConstraint(
            "event_type IN ('OPENED', 'ASSIGNED', 'NOTE', 'STATUS', 'DECISION', 'REOPENED')",
            name=op.f("ck_case_events_event_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_case_events_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["fraud_cases.id"],
            name=op.f("fk_case_events_case_id_fraud_cases"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_events")),
    )
    op.create_index("ix_case_events_case_id", "case_events", ["case_id"], unique=False)
    op.create_table(
        "ocr_results",
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column("engine_name", sa.String(length=50), nullable=False),
        sa.Column("engine_version", sa.String(length=100), nullable=False),
        sa.Column("pipeline_version", sa.String(length=100), nullable=False),
        sa.Column("selected_variant", sa.String(length=50), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("token_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("extracted_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("field_confidences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("required_field_accuracy_hint", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "required_field_accuracy_hint IS NULL OR (required_field_accuracy_hint >= 0 AND required_field_accuracy_hint <= 1)",
            name=op.f("ck_ocr_results_accuracy_hint_range"),
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["receipts.id"],
            name=op.f("fk_ocr_results_receipt_id_receipts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["receipt_templates.id"],
            name=op.f("fk_ocr_results_template_id_receipt_templates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ocr_results")),
    )
    op.create_index(
        "ix_ocr_results_receipt_created", "ocr_results", ["receipt_id", "created_at"], unique=False
    )
    op.create_table(
        "receipt_derivatives",
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("object_key", sa.String(length=500), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('THUMBNAIL', 'OCR_VARIANT', 'ELA', 'NOISE_MAP', 'HEATMAP')",
            name=op.f("ck_receipt_derivatives_kind_valid"),
        ),
        sa.CheckConstraint(
            "char_length(sha256) = 64", name=op.f("ck_receipt_derivatives_sha256_length")
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["receipts.id"],
            name=op.f("fk_receipt_derivatives_receipt_id_receipts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipt_derivatives")),
        sa.UniqueConstraint("object_key", name=op.f("uq_receipt_derivatives_object_key")),
        sa.UniqueConstraint(
            "receipt_id",
            "kind",
            "version",
            "sha256",
            name=op.f("uq_receipt_derivatives_receipt_id_kind_version_sha256"),
        ),
    )
    op.create_index(
        "ix_receipt_derivatives_receipt_id", "receipt_derivatives", ["receipt_id"], unique=False
    )
    op.create_table(
        "report_artifacts",
        sa.Column("report_type", sa.String(length=30), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("transaction_id", sa.Uuid(), nullable=True),
        sa.Column("case_id", sa.Uuid(), nullable=True),
        sa.Column("object_key", sa.String(length=500), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("generated_by", sa.Uuid(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(report_type = 'ANALYSIS' AND transaction_id IS NOT NULL AND case_id IS NULL) OR (report_type = 'CASE' AND case_id IS NOT NULL) OR (report_type = 'OPERATIONS' AND transaction_id IS NULL AND case_id IS NULL)",
            name=op.f("ck_report_artifacts_target_valid"),
        ),
        sa.CheckConstraint(
            "report_type IN ('ANALYSIS', 'CASE', 'OPERATIONS')",
            name=op.f("ck_report_artifacts_report_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('GENERATING', 'READY', 'FAILED', 'EXPIRED')",
            name=op.f("ck_report_artifacts_status_valid"),
        ),
        sa.CheckConstraint(
            "char_length(sha256) = 64", name=op.f("ck_report_artifacts_sha256_length")
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["fraud_cases.id"],
            name=op.f("fk_report_artifacts_case_id_fraud_cases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["generated_by"],
            ["users.id"],
            name=op.f("fk_report_artifacts_generated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_report_artifacts_owner_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_report_artifacts_transaction_id_transactions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_artifacts")),
        sa.UniqueConstraint("object_key", name=op.f("uq_report_artifacts_object_key")),
    )
    op.create_table(
        "ocr_confirmations",
        sa.Column("ocr_result_id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("confirmed_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("corrections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confirmed_by", sa.Uuid(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("schema_version", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["confirmed_by"],
            ["users.id"],
            name=op.f("fk_ocr_confirmations_confirmed_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ocr_result_id"],
            ["ocr_results.id"],
            name=op.f("fk_ocr_confirmations_ocr_result_id_ocr_results"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_ocr_confirmations_transaction_id_transactions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ocr_confirmations")),
    )
    op.create_index(
        "ix_ocr_confirmations_ocr_result_id", "ocr_confirmations", ["ocr_result_id"], unique=False
    )
    op.create_index(
        "ix_ocr_confirmations_transaction_confirmed",
        "ocr_confirmations",
        ["transaction_id", "confirmed_at"],
        unique=False,
    )
    op.create_table(
        "analysis_runs",
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("ocr_confirmation_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("current_stage", sa.String(length=50), nullable=True),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column("rule_set_id", sa.Uuid(), nullable=False),
        sa.Column("structured_model_id", sa.Uuid(), nullable=True),
        sa.Column("image_model_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key_hash", sa.String(length=64), nullable=True),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("claimed_by", sa.String(length=100), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("risk_score", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("risk_class", sa.String(length=20), nullable=True),
        sa.Column("component_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("top_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "configuration_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message_safe", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "risk_class IS NULL OR risk_class IN ('GENUINE', 'SUSPICIOUS', 'FRAUDULENT')",
            name=op.f("ck_analysis_runs_risk_class_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('QUEUED', 'PROCESSING', 'COMPLETED', 'PARTIAL', 'FAILED', 'CANCELLED')",
            name=op.f("ck_analysis_runs_status_valid"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_analysis_runs_attempt_count_nonnegative")
        ),
        sa.CheckConstraint(
            "char_length(request_fingerprint) = 64",
            name=op.f("ck_analysis_runs_fingerprint_length"),
        ),
        sa.CheckConstraint(
            "risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)",
            name=op.f("ck_analysis_runs_risk_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["image_model_id"],
            ["model_versions.id"],
            name=op.f("fk_analysis_runs_image_model_id_model_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ocr_confirmation_id"],
            ["ocr_confirmations.id"],
            name=op.f("fk_analysis_runs_ocr_confirmation_id_ocr_confirmations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rule_set_id"],
            ["fraud_rule_sets.id"],
            name=op.f("fk_analysis_runs_rule_set_id_fraud_rule_sets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["structured_model_id"],
            ["model_versions.id"],
            name=op.f("fk_analysis_runs_structured_model_id_model_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["receipt_templates.id"],
            name=op.f("fk_analysis_runs_template_id_receipt_templates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_analysis_runs_transaction_id_transactions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_runs")),
        sa.UniqueConstraint(
            "transaction_id",
            "idempotency_key_hash",
            name=op.f("uq_analysis_runs_transaction_id_idempotency_key_hash"),
        ),
    )
    op.create_index(
        "ix_analysis_runs_current_stage", "analysis_runs", ["current_stage"], unique=False
    )
    op.create_index(
        "ix_analysis_runs_risk_completed",
        "analysis_runs",
        ["risk_class", "completed_at"],
        unique=False,
    )
    op.create_index(
        "ix_analysis_runs_status_queued", "analysis_runs", ["status", "queued_at"], unique=False
    )
    op.create_index(
        "ix_analysis_runs_transaction_created",
        "analysis_runs",
        ["transaction_id", "created_at"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_transactions_latest_analysis_run_id_analysis_runs",
        "transactions",
        "analysis_runs",
        ["latest_analysis_run_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_table(
        "analysis_stage_runs",
        sa.Column("analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("stage", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'SKIPPED', 'FAILED')",
            name=op.f("ck_analysis_stage_runs_status_valid"),
        ),
        sa.CheckConstraint("attempt >= 1", name=op.f("ck_analysis_stage_runs_attempt_positive")),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0",
            name=op.f("ck_analysis_stage_runs_duration_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_analysis_stage_runs_analysis_run_id_analysis_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_stage_runs")),
        sa.UniqueConstraint(
            "analysis_run_id",
            "stage",
            "attempt",
            name=op.f("uq_analysis_stage_runs_analysis_run_id_stage_attempt"),
        ),
    )
    op.create_index(
        "ix_analysis_stage_runs_analysis_run_id",
        "analysis_stage_runs",
        ["analysis_run_id"],
        unique=False,
    )
    op.create_table(
        "fraud_predictions",
        sa.Column("analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("model_version_id", sa.Uuid(), nullable=False),
        sa.Column("prediction_type", sa.String(length=30), nullable=False),
        sa.Column("predicted_class", sa.String(length=20), nullable=True),
        sa.Column("probabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("feature_schema_hash", sa.String(length=64), nullable=False),
        sa.Column("feature_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("inference_ms", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "predicted_class IS NULL OR predicted_class IN ('GENUINE', 'SUSPICIOUS', 'FRAUDULENT')",
            name=op.f("ck_fraud_predictions_class_valid"),
        ),
        sa.CheckConstraint(
            "prediction_type IN ('STRUCTURED', 'IMAGE')",
            name=op.f("ck_fraud_predictions_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('SUCCESS', 'UNAVAILABLE', 'ERROR')",
            name=op.f("ck_fraud_predictions_status_valid"),
        ),
        sa.CheckConstraint(
            "char_length(feature_schema_hash) = 64",
            name=op.f("ck_fraud_predictions_schema_hash_length"),
        ),
        sa.CheckConstraint(
            "inference_ms IS NULL OR inference_ms >= 0",
            name=op.f("ck_fraud_predictions_inference_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_fraud_predictions_analysis_run_id_analysis_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_fraud_predictions_model_version_id_model_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fraud_predictions")),
        sa.UniqueConstraint(
            "analysis_run_id",
            "prediction_type",
            name=op.f("uq_fraud_predictions_analysis_run_id_prediction_type"),
        ),
    )
    op.create_index(
        "ix_fraud_predictions_analysis_run_id",
        "fraud_predictions",
        ["analysis_run_id"],
        unique=False,
    )
    op.create_table(
        "image_analyses",
        sa.Column("analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=100), nullable=False),
        sa.Column("metadata_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("duplicate_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("compression_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("noise_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("layout_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("quality_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("engineered_features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("image_tamper_probability", sa.Numeric(precision=7, scale=6), nullable=True),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "image_tamper_probability IS NULL OR (image_tamper_probability >= 0 AND image_tamper_probability <= 1)",
            name=op.f("ck_image_analyses_tamper_probability_range"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_image_analyses_analysis_run_id_analysis_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_image_analyses")),
        sa.UniqueConstraint("analysis_run_id", name=op.f("uq_image_analyses_analysis_run_id")),
    )
    op.create_table(
        "rule_evaluations",
        sa.Column("analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("triggered", sa.Boolean(), nullable=False),
        sa.Column("observed_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("score_contribution", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("reason_code", sa.String(length=100), nullable=False),
        sa.Column("reason_text", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "score_contribution >= 0", name=op.f("ck_rule_evaluations_score_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_rule_evaluations_analysis_run_id_analysis_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["fraud_rules.id"],
            name=op.f("fk_rule_evaluations_rule_id_fraud_rules"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_evaluations")),
        sa.UniqueConstraint(
            "analysis_run_id", "rule_id", name=op.f("uq_rule_evaluations_analysis_run_id_rule_id")
        ),
    )
    op.create_index(
        "ix_rule_evaluations_analysis_run_id", "rule_evaluations", ["analysis_run_id"], unique=False
    )
    op.create_table(
        "verification_results",
        sa.Column("analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("reference_transaction_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("verifier_version", sa.String(length=100), nullable=False),
        sa.Column("candidate_method", sa.String(length=100), nullable=False),
        sa.Column("field_comparisons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("matched_field_count", sa.Integer(), nullable=False),
        sa.Column("mismatched_field_count", sa.Integer(), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('VERIFIED', 'UNVERIFIED', 'MISMATCH')",
            name=op.f("ck_verification_results_status_valid"),
        ),
        sa.CheckConstraint(
            "matched_field_count >= 0", name=op.f("ck_verification_results_matched_nonnegative")
        ),
        sa.CheckConstraint(
            "mismatched_field_count >= 0",
            name=op.f("ck_verification_results_mismatched_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_verification_results_analysis_run_id_analysis_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reference_transaction_id"],
            ["reference_transactions.id"],
            name=op.f("fk_verification_results_reference_transaction_id_reference_transactions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_results")),
        sa.UniqueConstraint(
            "analysis_run_id", name=op.f("uq_verification_results_analysis_run_id")
        ),
    )
    op.create_index(
        "ix_verification_results_status_created",
        "verification_results",
        ["status", "created_at"],
        unique=False,
    )
    op.execute(
        """
        CREATE FUNCTION prevent_immutable_evidence_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'immutable evidence table % cannot be modified', TG_TABLE_NAME
                USING ERRCODE = '55000';
        END;
        $$ LANGUAGE plpgsql
        """
    )
    for table_name in (
        "audit_logs",
        "case_decisions",
        "case_events",
        "fraud_predictions",
        "image_analyses",
        "ocr_confirmations",
        "ocr_results",
        "receipt_derivatives",
        "rule_evaluations",
        "verification_results",
    ):
        op.execute(
            f"CREATE TRIGGER trg_{table_name}_immutable "
            f"BEFORE UPDATE OR DELETE ON {table_name} FOR EACH ROW "
            "EXECUTE FUNCTION prevent_immutable_evidence_mutation()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP FUNCTION prevent_immutable_evidence_mutation() CASCADE")
    op.drop_index("ix_verification_results_status_created", table_name="verification_results")
    op.drop_table("verification_results")
    op.drop_index("ix_rule_evaluations_analysis_run_id", table_name="rule_evaluations")
    op.drop_table("rule_evaluations")
    op.drop_table("image_analyses")
    op.drop_index("ix_fraud_predictions_analysis_run_id", table_name="fraud_predictions")
    op.drop_table("fraud_predictions")
    op.drop_index("ix_analysis_stage_runs_analysis_run_id", table_name="analysis_stage_runs")
    op.drop_table("analysis_stage_runs")
    op.drop_index("ix_analysis_runs_transaction_created", table_name="analysis_runs")
    op.drop_index("ix_analysis_runs_status_queued", table_name="analysis_runs")
    op.drop_index("ix_analysis_runs_risk_completed", table_name="analysis_runs")
    op.drop_index("ix_analysis_runs_current_stage", table_name="analysis_runs")
    op.drop_constraint(
        "fk_transactions_latest_analysis_run_id_analysis_runs",
        "transactions",
        type_="foreignkey",
    )
    op.drop_table("analysis_runs")
    op.drop_index("ix_ocr_confirmations_transaction_confirmed", table_name="ocr_confirmations")
    op.drop_index("ix_ocr_confirmations_ocr_result_id", table_name="ocr_confirmations")
    op.drop_table("ocr_confirmations")
    op.drop_table("report_artifacts")
    op.drop_index("ix_receipt_derivatives_receipt_id", table_name="receipt_derivatives")
    op.drop_table("receipt_derivatives")
    op.drop_index("ix_ocr_results_receipt_created", table_name="ocr_results")
    op.drop_table("ocr_results")
    op.drop_index("ix_case_events_case_id", table_name="case_events")
    op.drop_table("case_events")
    op.drop_index("ix_case_decisions_case_id", table_name="case_decisions")
    op.drop_table("case_decisions")
    op.drop_index(
        "uq_reference_transactions_source_id",
        table_name="reference_transactions",
        postgresql_where=sa.text("source_system_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_reference_transactions_provider_reference", table_name="reference_transactions"
    )
    op.drop_index("ix_reference_transactions_occurred_at", table_name="reference_transactions")
    op.drop_table("reference_transactions")
    op.drop_index("ix_receipts_sha256", table_name="receipts")
    op.drop_index("ix_receipts_perceptual_hash", table_name="receipts")
    op.drop_table("receipts")
    op.drop_index("ix_fraud_rules_rule_set_id", table_name="fraud_rules")
    op.drop_table("fraud_rules")
    op.drop_index(
        "uq_fraud_cases_active_transaction_source",
        table_name="fraud_cases",
        postgresql_where=sa.text("status IN ('OPEN', 'ASSIGNED', 'IN_REVIEW', 'REOPENED')"),
    )
    op.drop_index("ix_fraud_cases_transaction_id", table_name="fraud_cases")
    op.drop_index("ix_fraud_cases_status_assigned_opened", table_name="fraud_cases")
    op.drop_table("fraud_cases")
    op.drop_table("user_roles")
    op.drop_index("ix_transactions_user_created", table_name="transactions")
    op.drop_index("ix_transactions_status_created", table_name="transactions")
    op.drop_index("ix_transactions_provider_code", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index("ix_refresh_sessions_user_id", table_name="refresh_sessions")
    op.drop_index("ix_refresh_sessions_family_id", table_name="refresh_sessions")
    op.drop_index("ix_refresh_sessions_expires_at", table_name="refresh_sessions")
    op.drop_table("refresh_sessions")
    op.drop_index("ix_reference_import_batches_file_sha256", table_name="reference_import_batches")
    op.drop_table("reference_import_batches")
    op.drop_index(
        "uq_receipt_templates_active_provider",
        table_name="receipt_templates",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_table("receipt_templates")
    op.drop_index("ix_password_reset_tokens_user_id", table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_index("ix_notifications_user_read_created", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(
        "uq_model_versions_active_type_name",
        table_name="model_versions",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_table("model_versions")
    op.drop_index("ix_idempotency_records_expires_at", table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_index(
        "uq_fraud_rule_sets_active",
        table_name="fraud_rule_sets",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_table("fraud_rule_sets")
    op.drop_index("ix_audit_logs_target", table_name="audit_logs")
    op.drop_index("ix_audit_logs_request_id", table_name="audit_logs")
    op.drop_index("ix_audit_logs_created_at", table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor_created", table_name="audit_logs")
    op.drop_index("ix_audit_logs_action_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("admin_profiles")
    op.drop_index("ix_users_status", table_name="users")
    op.drop_table("users")
    op.drop_table("roles")
    # ### end Alembic commands ###
